Algoritmo "exer07"
// Calcular a média de quatro números inteiros dados.
Var
   n1, n2, n3, n4 : inteiro
   media : real
Inicio
     escreva("Digite o primeiro número: ")
     leia(n1)
     escreva("Digite o segundo número: ")
     leia(n2)
     escreva("Digite o terceiro número: ")
     leia(n3)
     escreva("Digite o quarto número: ")
     leia(n4)
     media := (n1 + n2 + n3 + n4) / 4
     escreva("A média = ", media)
Fimalgoritmo